"""empty message

Revision ID: b425f3c573eb
Revises: d41cccfc76cd
Create Date: 2017-11-22 11:30:53.746841

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b425f3c573eb'
down_revision = 'd41cccfc76cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bao_shop_user')
    op.drop_table('bao_common_attribute_key')
    op.drop_table('bao_backstage_user')
    op.drop_table('bao_common_attribute_value')
    op.drop_table('bao_user')
    op.add_column('bao_item', sa.Column('item_belong_shop_id', mysql.INTEGER(), nullable=False))
    op.add_column('bao_item', sa.Column('item_is_delete', mysql.SMALLINT(display_width=1), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bao_item', 'item_is_delete')
    op.drop_column('bao_item', 'item_belong_shop_id')
    op.create_table('bao_user',
    sa.Column('user_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('user_nickname', mysql.VARCHAR(length=32), nullable=True),
    sa.Column('user_name', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('user_verfy_code', mysql.VARCHAR(length=32), nullable=False),
    sa.Column('user_password', mysql.VARCHAR(length=32), nullable=False),
    sa.Column('user_mobile', mysql.VARCHAR(length=11), nullable=True),
    sa.Column('user_email', mysql.VARCHAR(length=32), nullable=True),
    sa.Column('user_ip', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('user_is_man', mysql.SMALLINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('user_id_card', mysql.VARCHAR(length=32), nullable=True),
    sa.Column('user_last_ip', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('user_status', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=False),
    sa.Column('user_current_login_time', mysql.VARCHAR(length=11), nullable=False),
    sa.Column('user_create_time', mysql.VARCHAR(length=11), nullable=False),
    sa.Column('user_logo', mysql.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('bao_common_attribute_value',
    sa.Column('value_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('attr_key_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('value', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('value_create_time', mysql.VARCHAR(length=11), nullable=False),
    sa.Column('value_update_time', mysql.VARCHAR(length=11), nullable=False),
    sa.Column('value_is_delete', mysql.SMALLINT(display_width=1), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('value_id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('bao_backstage_user',
    sa.Column('user_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('user_name', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('user_verfy_code', mysql.VARCHAR(length=32), nullable=False),
    sa.Column('user_password', mysql.VARCHAR(length=32), nullable=False),
    sa.Column('user_mobile', mysql.VARCHAR(length=11), nullable=True),
    sa.Column('user_email', mysql.VARCHAR(length=32), nullable=True),
    sa.Column('user_ip', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('user_is_man', mysql.SMALLINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('user_id_card', mysql.VARCHAR(length=32), nullable=True),
    sa.Column('user_last_ip', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('user_status', mysql.SMALLINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('user_current_login_time', mysql.VARCHAR(length=11), nullable=False),
    sa.Column('user_logo', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('user_permition', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('bao_common_attribute_key',
    sa.Column('attr_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('cate_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('attr_name', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('attr_index', mysql.SMALLINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('attr_order', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=False),
    sa.Column('is_linked', mysql.SMALLINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('attr_input_type', mysql.SMALLINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('attr_values', mysql.TEXT(), nullable=False),
    sa.Column('attr_group', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=False),
    sa.Column('attr_can_muti', mysql.SMALLINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('attr_create_time', mysql.VARCHAR(length=11), nullable=False),
    sa.Column('attr_update_time', mysql.VARCHAR(length=11), nullable=True),
    sa.Column('attr_is_delete', mysql.SMALLINT(display_width=1), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('attr_id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('bao_shop_user',
    sa.Column('user_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('user_name', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('user_verfy_code', mysql.VARCHAR(length=32), nullable=False),
    sa.Column('user_password', mysql.VARCHAR(length=32), nullable=False),
    sa.Column('user_mobile', mysql.VARCHAR(length=11), nullable=True),
    sa.Column('user_email', mysql.VARCHAR(length=32), nullable=True),
    sa.Column('user_ip', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('user_is_man', mysql.SMALLINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('user_id_card', mysql.VARCHAR(length=32), nullable=True),
    sa.Column('user_last_ip', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('user_status', mysql.SMALLINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('user_current_login_time', mysql.VARCHAR(length=11), nullable=False),
    sa.Column('user_logo', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('user_permition', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
