"""empty message

Revision ID: d41cccfc76cd
Revises: 
Create Date: 2017-11-16 16:15:45.057679

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd41cccfc76cd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bao_blog_detail')
    op.drop_table('bao_common_attribute_key')
    op.drop_table('Bao_user_login_record')
    op.drop_table('bao_common_attribute_value')
    op.add_column('bao_cate', sa.Column('cate_create_time', sa.DATE(), nullable=False))
    op.add_column('bao_cate', sa.Column('cate_update_time', sa.DATE(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bao_cate', 'cate_update_time')
    op.drop_column('bao_cate', 'cate_create_time')
    op.create_table('bao_common_attribute_value',
    sa.Column('value_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('attr_key_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('value', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('value_create_time', sa.DATE(), nullable=False),
    sa.Column('value_update_time', sa.DATE(), nullable=True),
    sa.Column('value_is_delete', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('value_id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('Bao_user_login_record',
    sa.Column('v_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('v_host', mysql.TEXT(), nullable=True),
    sa.Column('v_time', mysql.TEXT(), nullable=True),
    sa.Column('v_agent', mysql.TEXT(), nullable=True),
    sa.Column('v_referer', mysql.TEXT(), nullable=True),
    sa.Column('v_encoding', mysql.TEXT(), nullable=True),
    sa.Column('v_language', mysql.TEXT(), nullable=True),
    sa.Column('v_ip', mysql.TEXT(), nullable=True),
    sa.Column('v_user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('v_id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('bao_common_attribute_key',
    sa.Column('attr_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('cate_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('attr_name', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('attr_index', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=False),
    sa.Column('attr_order', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=False),
    sa.Column('is_linked', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=False),
    sa.Column('attr_input_type', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=False),
    sa.Column('attr_values', mysql.TEXT(), nullable=False),
    sa.Column('attr_group', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=False),
    sa.Column('attr_can_muti', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=False),
    sa.Column('attr_create_time', sa.DATE(), nullable=False),
    sa.Column('attr_update_time', sa.DATE(), nullable=True),
    sa.Column('attr_is_delete', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('attr_id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('bao_blog_detail',
    sa.Column('blog_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('blog_title', mysql.TEXT(), nullable=False),
    sa.Column('blog_subheading', mysql.TEXT(), nullable=True),
    sa.Column('blog_create_time_tuple', mysql.VARCHAR(length=32), nullable=False),
    sa.Column('blog_current_edit_tuple', mysql.VARCHAR(length=32), nullable=False),
    sa.Column('blog_content', mysql.TEXT(), nullable=True),
    sa.Column('blog_creater_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('blog_id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
